add_rules("mode.debug", "mode.release")
add_rules("plugin.compile_commands.autoupdate", {outputdir = "build"})

set_project("planka-mcp")
set_version("26.03.22")
set_languages("c++20")
add_cxflags("-static-libstdc++", "-static-libgcc", {force = true})
add_ldflags("-static-libstdc++", "-static-libgcc", {force = true})

includes("packages/workflow/xmake.lua")
includes("packages/wfrest/xmake.lua")
includes("packages/coke/xmake.lua")
includes("packages/maplog/xmake.lua")

add_requires("openssl", {system = true})
add_requires("zlib", {configs = {shared = false}})
add_requires("workflow", {configs = {shared = false}})
add_requires("wfrest", {configs = {shared = false}})
add_requires("coke", {configs = {shared = false}})
add_requires("maplog", {configs = {shared = false}})

-- 主程序构建目标
target("planka-mcp")
    set_kind("binary")
    add_configfiles("src/config.h.in")
    add_includedirs("src")
    add_includedirs("$(builddir)")
    add_files("src/**.cpp")
    add_packages("workflow", "wfrest", "coke", "openssl", "maplog")

-- 测试目标 (TDD 约束入口)
target("test_planka_mcp")
    set_kind("binary")
    add_configfiles("src/config.h.in")
    add_includedirs("src", "tests")
    add_includedirs("$(builddir)")
    add_files("src/**.cpp|main.cpp")
    add_files("tests/**.cpp")
    add_packages("workflow", "wfrest", "coke", "openssl", "maplog")
